server:
  port: :8080

postgres:
  host: host
  port: '5432'
  user: user
  password: password
  db_name: dbname
  ssl_mode: disable

jwt:
  secret: secret
  expires_in: 1h0m0s
  refresh_secret: refreshsecret
  refresh_expires_in: 72h0m0s
