server:
  port: ':8080'

postgres:
  host: ''
  port: ''
  user: ''
  password: ''
  db_name: ''
  ssl_mode: false

jwt:
  secret: ''
  expires_in: '1h0m0s'
  refresh_secret: ''
  refresh_expires_in: '72h0m0s'
